services:
  - type: web
    name: excelgenautomationdevo
    env: static
    buildCommand: flutter pub get && flutter build web --release --dart-define=SUPABASE_URL=$SUPABASE_URL --dart-define=SUPABASE_PUBLISHABLE_KEY=$SUPABASE_PUBLISHABLE_KEY
    staticPublishPath: build/web
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
