// Generated by UI Builder
// ui_builder:editable=true
import 'package:flutter/material.dart';

class MasterData extends StatelessWidget {
  const MasterData({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Text('master_data.dart'),
      ),
    );
  }
}
