// Generated by UI Builder
// ui_builder:editable=true
import 'package:flutter/material.dart';

class PivotEngine extends StatelessWidget {
  const PivotEngine({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Text('pivot_engine.dart'),
      ),
    );
  }
}
