// Generated by UI Builder
// ui_builder:editable=true
import 'dart:math' as math;

import 'package:excelgenautomationdevo/screens/common/master_data.dart';
import 'package:excelgenautomationdevo/screens/dashboard/dispatcher_dashboard.dart';
import 'package:flutter/material.dart';

import 'dispatcher_shell.dart';

class PivotEngine extends StatelessWidget {
  const PivotEngine({super.key});

  static const _selectedDates = [
    '5/14/2026',
    '5/13/2026',
    '5/12/2026',
    '5/11/2026',
  ];

  static const _selectedPlants = [
    ('AMBATTUR', Color(0xFFFFE8D6), Color(0xFF9A5A1F)),
    ('KATTUR', Color(0xFFFFE8D6), Color(0xFF9A5A1F)),
    ('#N/A', Color(0xFFFFE8D6), Color(0xFF9A5A1F)),
    ('Plant Missing', Color(0xFFF1F5F9), Color(0xFF2563EB)),
  ];

  static const _selectedProjects = [
    'EX250438L005',
    'EX250438L007',
    'EX250438L008',
    'IN003688L021',
  ];

  static const _partRows = [
    ('0032WFDG01_LLF_M35B_WRG700', '3'),
    ('0032WHCG01_WYJ103-08', '3'),
    ('0032WJRG01', '8'),
    ('0048WLT015', '6'),
    ('0063WHXG01_LH_WRG700_5XD10_T89-B', '1'),
    ('0063WJGG01_LH', '1'),
    ('0063WJGG02_LH', '2'),
    ('0063WJNG01_LH', '2'),
    ('0063WJPG01_IW1200_PTP2000_CL1020_LA125_LB125_LH', '2'),
    ('0063WKC01_T78_LH', '8'),
    ('0098ZCRG01_LH_T89-B', '1'),
    ('0122WVCL015', '6'),
    ('0122WCR015', '3'),
    ('0211WBSG01', '2'),
    ('0211WBTG01', '4'),
  ];

  static const _topParts = [
    _LegendDatum(
      label: '00310WBFG01_S_T89-1B',
      value: '72',
      color: Color(0xFF2563EB),
      percentage: 0.37,
    ),
    _LegendDatum(
      label: '00310WBFG01_S_T89-B',
      value: '46',
      color: Color(0xFF59C153),
      percentage: 0.24,
    ),
    _LegendDatum(
      label: '0032WJRG01',
      value: '8',
      color: Color(0xFFFFC62B),
      percentage: 0.18,
    ),
    _LegendDatum(
      label: '0063WKC01_T78_LH',
      value: '8',
      color: Color(0xFF8B5CF6),
      percentage: 0.14,
    ),
    _LegendDatum(
      label: '0048WLT015',
      value: '6',
      color: Color(0xFF22C7E5),
      percentage: 0.07,
    ),
  ];

  static const _plantSummary = [
    ('AMBATTUR', '812'),
    ('KATTUR', '497'),
    ('#N/A', '59'),
    ('Plant Missing', '-'),
  ];

  @override
  Widget build(BuildContext context) {
    return DispatcherScaffold(
      currentItem: DispatcherNavItem.pivot,
      backgroundColor: const Color(0xFFF5F7FB),
      onItemSelected: (item) => _handleNavigation(context, item),
      body: LayoutBuilder(
        builder: (context, constraints) {
          final isDesktop = constraints.maxWidth >= 1320;

          return SingleChildScrollView(
            padding: EdgeInsets.all(isDesktop ? 18 : 12),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _PivotHeader(isDesktop: isDesktop),
                const SizedBox(height: 16),
                _ActionBar(isDesktop: isDesktop),
                const SizedBox(height: 16),
                _FilterAndStatsSection(isDesktop: isDesktop),
                const SizedBox(height: 16),
                _BottomSection(isDesktop: isDesktop),
              ],
            ),
          );
        },
      ),
    );
  }

  void _handleNavigation(BuildContext context, DispatcherNavItem item) {
    if (item == DispatcherNavItem.pivot) return;

    final page = switch (item) {
      DispatcherNavItem.master => const MasterData(),
      DispatcherNavItem.dashboard => const DispatcherDashboard(),
      DispatcherNavItem.pivot => const PivotEngine(),
    };

    navigateWithDispatcherTransition(context, page);
  }
}

// ignore: unused_element
class _PivotSidebar extends StatelessWidget {
  const _PivotSidebar();

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 250,
      margin: const EdgeInsets.all(18),
      decoration: const BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment.topCenter,
          end: Alignment.bottomCenter,
          colors: [Color(0xFF0B2A5B), Color(0xFF071A3A)],
        ),
        borderRadius: BorderRadius.all(Radius.circular(28)),
      ),
      child: const Column(
        children: [
          SizedBox(height: 24),
          _SidebarBrand(),
          SizedBox(height: 18),
          _SidebarProfile(),
          SizedBox(height: 18),
          _SidebarTile(icon: Icons.dashboard_outlined, label: 'Dashboard'),
          _SidebarTile(icon: Icons.upload_file_outlined, label: 'File Upload'),
          _SidebarTile(icon: Icons.apartment_outlined, label: 'Plant Update'),
          _SidebarTile(
            icon: Icons.calendar_month_outlined,
            label: 'Schedule Update',
          ),
          _SidebarTile(icon: Icons.storage_outlined, label: 'Master Data'),
          _SidebarTile(
            icon: Icons.table_chart_outlined,
            label: 'Pivot Summary',
            selected: true,
          ),
          _SidebarTile(
            icon: Icons.local_shipping_outlined,
            label: 'Dispatch Update',
          ),
          _SidebarTile(
            icon: Icons.dashboard_customize_outlined,
            label: 'Dedicated Dashboard',
          ),
          Spacer(),
          Divider(color: Color(0x33FFFFFF), indent: 20, endIndent: 20),
          SizedBox(height: 12),
          _SidebarTile(icon: Icons.notifications_none, label: 'Notifications'),
          _SidebarTile(icon: Icons.logout, label: 'Logout'),
          SizedBox(height: 18),
        ],
      ),
    );
  }
}

class _SidebarBrand extends StatelessWidget {
  const _SidebarBrand();

  @override
  Widget build(BuildContext context) {
    return const Padding(
      padding: EdgeInsets.symmetric(horizontal: 18),
      child: Row(
        children: [
          CircleAvatar(
            radius: 18,
            backgroundColor: Color(0xFF2563EB),
            child: Icon(Icons.inventory_2_rounded, color: Colors.white),
          ),
          SizedBox(width: 12),
          Text(
            'SupplyTrack',
            style: TextStyle(
              color: Colors.white,
              fontWeight: FontWeight.w700,
              fontSize: 20,
            ),
          ),
        ],
      ),
    );
  }
}

class _SidebarProfile extends StatelessWidget {
  const _SidebarProfile();

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 16),
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: Colors.white.withValues(alpha: 0.08),
        borderRadius: BorderRadius.circular(18),
        border: Border.all(color: Colors.white.withValues(alpha: 0.12)),
      ),
      child: const Row(
        children: [
          CircleAvatar(
            radius: 22,
            backgroundColor: Colors.white,
            child: Text(
              'DU',
              style: TextStyle(
                color: Color(0xFF2563EB),
                fontWeight: FontWeight.w700,
              ),
            ),
          ),
          SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  'Dispatch User',
                  style: TextStyle(
                    color: Colors.white,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                SizedBox(height: 2),
                Text(
                  'Dispatcher',
                  style: TextStyle(
                    color: Color(0xFFBFDBFE),
                    fontSize: 12,
                  ),
                ),
              ],
            ),
          ),
          Icon(Icons.keyboard_arrow_down, color: Colors.white),
        ],
      ),
    );
  }
}

class _SidebarTile extends StatelessWidget {
  const _SidebarTile({
    required this.icon,
    required this.label,
    this.selected = false,
  });

  final IconData icon;
  final String label;
  final bool selected;

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 12, vertical: 4),
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
      decoration: BoxDecoration(
        color: selected ? const Color(0xFF2563EB) : Colors.transparent,
        borderRadius: BorderRadius.circular(16),
      ),
      child: Row(
        children: [
          Icon(icon, color: Colors.white, size: 22),
          const SizedBox(width: 12),
          Text(
            label,
            style: const TextStyle(
              color: Colors.white,
              fontWeight: FontWeight.w600,
            ),
          ),
        ],
      ),
    );
  }
}

class _PivotHeader extends StatelessWidget {
  const _PivotHeader({required this.isDesktop});

  final bool isDesktop;

  @override
  Widget build(BuildContext context) {
    final titleCard = Container(
      padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 14),
      decoration: _panelDecoration(),
      child: const Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(Icons.menu_rounded, color: Color(0xFF475569)),
          SizedBox(width: 18),
          Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'PIVOT SUMMARY',
                style: TextStyle(
                  color: Color(0xFF172554),
                  fontSize: 24,
                  fontWeight: FontWeight.w800,
                ),
              ),
              SizedBox(height: 4),
              Text(
                'Quick view of parts by selected filters',
                style: TextStyle(
                  color: Color(0xFF64748B),
                  fontWeight: FontWeight.w600,
                ),
              ),
            ],
          ),
        ],
      ),
    );

    final searchCard = Container(
      height: 60,
      padding: const EdgeInsets.symmetric(horizontal: 18),
      decoration: _panelDecoration(),
      child: const Row(
        children: [
          Expanded(
            child: TextField(
              decoration: InputDecoration(
                hintText:
                    'Search PR Detail No, Part Number, Project, Description...',
                border: InputBorder.none,
                hintStyle: TextStyle(color: Color(0xFF94A3B8)),
              ),
            ),
          ),
          Icon(Icons.search_rounded, color: Color(0xFF64748B)),
        ],
      ),
    );

    final profileCard = Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      decoration: _panelDecoration(),
      child: const Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Stack(
            clipBehavior: Clip.none,
            children: [
              Icon(Icons.notifications_none_rounded, color: Color(0xFF475569)),
              Positioned(
                right: -2,
                top: -4,
                child: CircleAvatar(
                  radius: 8,
                  backgroundColor: Color(0xFFEF4444),
                  child: Text(
                    '8',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 9,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
            ],
          ),
          SizedBox(width: 14),
          CircleAvatar(
            radius: 18,
            backgroundColor: Color(0xFF0F2F6F),
            child: Text(
              'DU',
              style: TextStyle(
                color: Colors.white,
                fontWeight: FontWeight.w700,
              ),
            ),
          ),
          SizedBox(width: 10),
          Text(
            'Dispatch User',
            style: TextStyle(
              color: Color(0xFF0F172A),
              fontWeight: FontWeight.w600,
            ),
          ),
          SizedBox(width: 4),
          Icon(Icons.keyboard_arrow_down_rounded, color: Color(0xFF64748B)),
        ],
      ),
    );

    if (!isDesktop) {
      return Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          titleCard,
          const SizedBox(height: 12),
          searchCard,
          const SizedBox(height: 12),
          Align(alignment: Alignment.centerRight, child: profileCard),
        ],
      );
    }

    return Row(
      children: [
        titleCard,
        const SizedBox(width: 16),
        Expanded(child: searchCard),
        const SizedBox(width: 16),
        profileCard,
      ],
    );
  }
}

class _ActionBar extends StatelessWidget {
  const _ActionBar({required this.isDesktop});

  final bool isDesktop;

  @override
  Widget build(BuildContext context) {
    const actions = Wrap(
      spacing: 12,
      runSpacing: 12,
      alignment: WrapAlignment.end,
      children: [
        _ActionButton(
          label: 'Print PDF',
          icon: Icons.print_outlined,
          color: Color(0xFF2563EB),
        ),
        _ActionButton(
          label: 'Export Excel',
          icon: Icons.file_download_outlined,
          color: Color(0xFF4CAF50),
        ),
        _ActionButton(
          label: 'Clear All & Refresh',
          icon: Icons.refresh_rounded,
          color: Color(0xFFEF4444),
        ),
      ],
    );

    if (!isDesktop) {
      return actions;
    }

    return const Row(
      mainAxisAlignment: MainAxisAlignment.end,
      children: [Expanded(child: actions)],
    );
  }
}

class _ActionButton extends StatelessWidget {
  const _ActionButton({
    required this.label,
    required this.icon,
    required this.color,
  });

  final String label;
  final IconData icon;
  final Color color;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 22, vertical: 14),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: color.withValues(alpha: 0.45)),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, color: color, size: 22),
          const SizedBox(width: 10),
          Text(
            label,
            style: TextStyle(
              color: color,
              fontWeight: FontWeight.w700,
            ),
          ),
        ],
      ),
    );
  }
}

class _FilterAndStatsSection extends StatelessWidget {
  const _FilterAndStatsSection({required this.isDesktop});

  final bool isDesktop;

  @override
  Widget build(BuildContext context) {
    const left = Expanded(
      flex: 5,
      child: Column(
        children: [
          Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(
                child: _SelectionCard(
                  title: 'MRD DATE',
                  chips: PivotEngine._selectedDates,
                  chipStyle: _ChipVisual.green,
                  footerText: '+1 more',
                  trailingIcon: Icons.calendar_month_outlined,
                ),
              ),
              SizedBox(width: 12),
              Expanded(
                child: _PlantCodeCard(),
              ),
              SizedBox(width: 12),
              Expanded(
                child: _ProjectCard(),
              ),
            ],
          ),
          SizedBox(height: 12),
          _DropdownFiltersCard(),
        ],
      ),
    );

    final right = SizedBox(
      width: isDesktop ? 320 : double.infinity,
      child: const _StatsColumn(),
    );

    if (!isDesktop) {
      return Column(
        children: [
          const _SelectionCard(
            title: 'MRD DATE',
            chips: PivotEngine._selectedDates,
            chipStyle: _ChipVisual.green,
            footerText: '+1 more',
            trailingIcon: Icons.calendar_month_outlined,
          ),
          const SizedBox(height: 12),
          const _PlantCodeCard(),
          const SizedBox(height: 12),
          const _ProjectCard(),
          const SizedBox(height: 12),
          const _DropdownFiltersCard(),
          const SizedBox(height: 12),
          right,
        ],
      );
    }

    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        left,
        const SizedBox(width: 12),
        right,
      ],
    );
  }
}

enum _ChipVisual { green, orange, neutral }

class _SelectionCard extends StatelessWidget {
  const _SelectionCard({
    required this.title,
    required this.chips,
    required this.chipStyle,
    this.footerText,
    this.trailingIcon,
  });

  final String title;
  final List<String> chips;
  final _ChipVisual chipStyle;
  final String? footerText;
  final IconData? trailingIcon;

  @override
  Widget build(BuildContext context) {
    final colors = switch (chipStyle) {
      _ChipVisual.green => (const Color(0xFFDDF5DE), const Color(0xFF2B8E41)),
      _ChipVisual.orange => (const Color(0xFFFFE8D6), const Color(0xFF9A5A1F)),
      _ChipVisual.neutral => (const Color(0xFFF1F5F9), const Color(0xFF2563EB)),
    };

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: _panelDecoration(),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Expanded(
                child: Text(
                  title,
                  style: const TextStyle(
                    color: Color(0xFF1E293B),
                    fontWeight: FontWeight.w800,
                    fontSize: 14,
                  ),
                ),
              ),
              if (trailingIcon != null)
                Icon(trailingIcon, color: const Color(0xFF64748B)),
            ],
          ),
          const SizedBox(height: 12),
          ...chips.map(
            (chip) => Padding(
              padding: const EdgeInsets.only(bottom: 8),
              child: Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                decoration: BoxDecoration(
                  color: colors.$1,
                  borderRadius: BorderRadius.circular(10),
                ),
                child: Row(
                  children: [
                    Expanded(
                      child: Text(
                        chip,
                        style: TextStyle(
                          color: colors.$2,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                    const Icon(Icons.close, size: 16, color: Color(0xFF64748B)),
                  ],
                ),
              ),
            ),
          ),
          if (footerText != null)
            Text(
              footerText!,
              style: const TextStyle(
                color: Color(0xFF2563EB),
                fontWeight: FontWeight.w700,
              ),
            ),
        ],
      ),
    );
  }
}

class _PlantCodeCard extends StatelessWidget {
  const _PlantCodeCard();

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: _panelDecoration(),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Row(
            children: [
              Expanded(
                child: Text(
                  'PLANT CODE',
                  style: TextStyle(
                    color: Color(0xFF1E293B),
                    fontWeight: FontWeight.w800,
                    fontSize: 14,
                  ),
                ),
              ),
              Icon(Icons.filter_alt_outlined,
                  color: Color(0xFF64748B), size: 20),
            ],
          ),
          const SizedBox(height: 12),
          ...PivotEngine._selectedPlants.map(
            (chip) => Padding(
              padding: const EdgeInsets.only(bottom: 8),
              child: Container(
                padding:
                    const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                decoration: BoxDecoration(
                  color: chip.$2,
                  borderRadius: BorderRadius.circular(10),
                ),
                child: Row(
                  children: [
                    Expanded(
                      child: Text(
                        chip.$1,
                        style: TextStyle(
                          color: chip.$3,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                    const Icon(Icons.close, size: 16, color: Color(0xFF64748B)),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _ProjectCard extends StatelessWidget {
  const _ProjectCard();

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: _panelDecoration(),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'PROJECT',
            style: TextStyle(
              color: Color(0xFF1E293B),
              fontWeight: FontWeight.w800,
              fontSize: 14,
            ),
          ),
          const SizedBox(height: 12),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
            decoration: BoxDecoration(
              color: const Color(0xFFF8FAFC),
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: const Color(0xFFDCE4F2)),
            ),
            child: const Row(
              children: [
                Expanded(
                  child: Text(
                    'Search project...',
                    style: TextStyle(color: Color(0xFF94A3B8)),
                  ),
                ),
                Icon(Icons.search_rounded, color: Color(0xFF64748B)),
              ],
            ),
          ),
          const SizedBox(height: 12),
          ...PivotEngine._selectedProjects.map(
            (project) => Padding(
              padding: const EdgeInsets.only(bottom: 8),
              child: Container(
                width: double.infinity,
                padding:
                    const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
                decoration: BoxDecoration(
                  color: const Color(0xFFF1F5F9),
                  borderRadius: BorderRadius.circular(10),
                ),
                child: Text(
                  project,
                  style: const TextStyle(
                    color: Color(0xFF475569),
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
            ),
          ),
          const Text(
            '+ 124 more',
            style: TextStyle(
              color: Color(0xFF2563EB),
              fontWeight: FontWeight.w700,
            ),
          ),
        ],
      ),
    );
  }
}

class _DropdownFiltersCard extends StatelessWidget {
  const _DropdownFiltersCard();

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: _panelDecoration(),
      child: const Column(
        children: [
          Row(
            children: [
              Expanded(
                child: _DropdownField(
                  label: 'MRD DATE',
                  value: '(All)',
                ),
              ),
              SizedBox(width: 16),
              Expanded(
                child: _DropdownField(
                  label: 'PLANT CODE',
                  value: '(All)',
                ),
              ),
            ],
          ),
          SizedBox(height: 16),
          Row(
            children: [
              Expanded(
                child: _DropdownField(
                  label: 'Project',
                  value: '(All)',
                ),
              ),
              SizedBox(width: 16),
              Expanded(child: SizedBox()),
            ],
          ),
        ],
      ),
    );
  }
}

class _DropdownField extends StatelessWidget {
  const _DropdownField({
    required this.label,
    required this.value,
  });

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          label,
          style: const TextStyle(
            color: Color(0xFF1E3A8A),
            fontWeight: FontWeight.w700,
          ),
        ),
        const SizedBox(height: 10),
        Container(
          height: 44,
          padding: const EdgeInsets.symmetric(horizontal: 14),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: const Color(0xFFDCE4F2)),
          ),
          child: Row(
            children: [
              Expanded(
                child: Text(
                  value,
                  style: const TextStyle(
                    color: Color(0xFF334155),
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              const Icon(Icons.keyboard_arrow_down_rounded,
                  color: Color(0xFF64748B)),
            ],
          ),
        ),
      ],
    );
  }
}

class _StatsColumn extends StatelessWidget {
  const _StatsColumn();

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: _panelDecoration(),
      child: const Column(
        children: [
          _MetricCard(
            dark: true,
            title: 'Total QTY',
            value: '1,309',
            icon: Icons.inventory_2_outlined,
          ),
          SizedBox(height: 12),
          _MetricCard(
            dark: false,
            title: 'No. of Parts',
            value: '59',
            icon: Icons.widgets_outlined,
          ),
        ],
      ),
    );
  }
}

class _MetricCard extends StatelessWidget {
  const _MetricCard({
    required this.dark,
    required this.title,
    required this.value,
    required this.icon,
  });

  final bool dark;
  final String title;
  final String value;
  final IconData icon;

  @override
  Widget build(BuildContext context) {
    final background = dark ? const Color(0xFF0A2B60) : Colors.white;
    final foreground = dark ? Colors.white : const Color(0xFF0F172A);
    final accent = dark ? Colors.white70 : const Color(0xFF94A3B8);

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: background,
        borderRadius: BorderRadius.circular(18),
        border: Border.all(
          color: dark ? const Color(0xFF0A2B60) : const Color(0xFFE5EAF2),
        ),
      ),
      child: Row(
        children: [
          Icon(icon, color: accent, size: 34),
          const SizedBox(width: 14),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  title,
                  style: TextStyle(
                    color: dark ? Colors.white70 : const Color(0xFF334155),
                    fontWeight: FontWeight.w600,
                  ),
                ),
                const SizedBox(height: 6),
                Text(
                  value,
                  style: TextStyle(
                    color: foreground,
                    fontSize: 24,
                    fontWeight: FontWeight.w800,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _BottomSection extends StatelessWidget {
  const _BottomSection({required this.isDesktop});

  final bool isDesktop;

  @override
  Widget build(BuildContext context) {
    final tableCard = Expanded(
      flex: 5,
      child: Container(
        decoration: _panelDecoration(),
        child: const _PivotTableCard(),
      ),
    );

    final sidePanel = SizedBox(
      width: isDesktop ? 320 : double.infinity,
      child: const Column(
        children: [
          _TopPartsCard(),
          SizedBox(height: 16),
          _PlantSummaryCard(),
        ],
      ),
    );

    if (!isDesktop) {
      return Column(
        children: [
          const _PivotTableCard(),
          const SizedBox(height: 16),
          sidePanel,
        ],
      );
    }

    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        tableCard,
        const SizedBox(width: 12),
        sidePanel,
      ],
    );
  }
}

class _PivotTableCard extends StatelessWidget {
  const _PivotTableCard();

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: _panelDecoration(),
      child: Column(
        children: [
          Container(
            padding: const EdgeInsets.symmetric(vertical: 14, horizontal: 14),
            decoration: BoxDecoration(
              color: const Color(0xFFF8FAFF),
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: const Color(0xFFE5EAF2)),
            ),
            child: const Row(
              children: [
                Expanded(
                  child: Text(
                    'Part Number',
                    style: TextStyle(
                      color: Color(0xFF1E293B),
                      fontWeight: FontWeight.w800,
                    ),
                  ),
                ),
                SizedBox(
                  width: 96,
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: [
                      Text(
                        'QTY',
                        style: TextStyle(
                          color: Color(0xFF1E293B),
                          fontWeight: FontWeight.w800,
                        ),
                      ),
                      SizedBox(width: 6),
                      Icon(Icons.swap_vert, size: 18, color: Color(0xFF64748B)),
                    ],
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 6),
          ...PivotEngine._partRows.map(
            (row) => Container(
              padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
              decoration: const BoxDecoration(
                border: Border(
                  bottom: BorderSide(color: Color(0xFFEFF3F8)),
                ),
              ),
              child: Row(
                children: [
                  Expanded(
                    child: Text(
                      row.$1,
                      style: const TextStyle(
                        color: Color(0xFF334155),
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                  SizedBox(
                    width: 96,
                    child: Text(
                      row.$2,
                      textAlign: TextAlign.right,
                      style: const TextStyle(
                        color: Color(0xFF334155),
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
          const SizedBox(height: 18),
          LayoutBuilder(
            builder: (context, constraints) {
              final compact = constraints.maxWidth < 760;

              const footer = Wrap(
                spacing: 12,
                runSpacing: 12,
                crossAxisAlignment: WrapCrossAlignment.center,
                children: [
                  Text(
                    'Showing 1 to 15 of 59 entries',
                    style: TextStyle(
                      color: Color(0xFF475569),
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                  _PaginationBar(),
                  _RowsPerPageChip(),
                ],
              );

              if (compact) {
                return const Align(
                    alignment: Alignment.centerLeft, child: footer);
              }

              return const Row(
                children: [
                  Text(
                    'Showing 1 to 15 of 59 entries',
                    style: TextStyle(
                      color: Color(0xFF475569),
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                  Spacer(),
                  _PaginationBar(),
                  SizedBox(width: 20),
                  _RowsPerPageChip(),
                ],
              );
            },
          ),
        ],
      ),
    );
  }
}

class _PaginationBar extends StatelessWidget {
  const _PaginationBar();

  @override
  Widget build(BuildContext context) {
    Widget button(String label, {bool active = false, bool wide = false}) {
      return Container(
        width: wide ? 44 : 36,
        height: 36,
        alignment: Alignment.center,
        decoration: BoxDecoration(
          color: active ? const Color(0xFF2563EB) : Colors.white,
          borderRadius: BorderRadius.circular(10),
          border: Border.all(
            color: active ? const Color(0xFF2563EB) : const Color(0xFFDCE4F2),
          ),
        ),
        child: Text(
          label,
          style: TextStyle(
            color: active ? Colors.white : const Color(0xFF334155),
            fontWeight: FontWeight.w700,
          ),
        ),
      );
    }

    return Wrap(
      spacing: 8,
      runSpacing: 8,
      children: [
        button('≪'),
        button('‹'),
        button('1', active: true),
        button('2'),
        button('3'),
        button('4'),
        button('...'),
        button('4'),
        button('›'),
        button('≫'),
      ],
    );
  }
}

class _RowsPerPageChip extends StatelessWidget {
  const _RowsPerPageChip();

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: const Color(0xFFDCE4F2)),
      ),
      child: const Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(
            'Rows per page: 15',
            style: TextStyle(
              color: Color(0xFF334155),
              fontWeight: FontWeight.w600,
            ),
          ),
          SizedBox(width: 8),
          Icon(Icons.keyboard_arrow_down_rounded, color: Color(0xFF64748B)),
        ],
      ),
    );
  }
}

class _TopPartsCard extends StatelessWidget {
  const _TopPartsCard();

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: _panelDecoration(),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'Top 5 Part Numbers',
            style: TextStyle(
              color: Color(0xFF172554),
              fontSize: 16,
              fontWeight: FontWeight.w800,
            ),
          ),
          const SizedBox(height: 18),
          const Center(
            child: SizedBox(
              width: 190,
              height: 190,
              child: _DonutChart(data: PivotEngine._topParts),
            ),
          ),
          const SizedBox(height: 18),
          ...PivotEngine._topParts.map(
            (part) => Padding(
              padding: const EdgeInsets.only(bottom: 12),
              child: Row(
                children: [
                  Container(
                    width: 10,
                    height: 10,
                    decoration: BoxDecoration(
                      color: part.color,
                      shape: BoxShape.circle,
                    ),
                  ),
                  const SizedBox(width: 10),
                  Expanded(
                    child: Text(
                      part.label,
                      style: const TextStyle(
                        color: Color(0xFF334155),
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                  Text(
                    part.value,
                    style: const TextStyle(
                      color: Color(0xFF334155),
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _PlantSummaryCard extends StatelessWidget {
  const _PlantSummaryCard();

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(16),
      decoration: _panelDecoration(),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'Summary by Plant',
            style: TextStyle(
              color: Color(0xFF172554),
              fontSize: 16,
              fontWeight: FontWeight.w800,
            ),
          ),
          const SizedBox(height: 14),
          Container(
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: const Color(0xFFE5EAF2)),
            ),
            child: Column(
              children: [
                Container(
                  padding:
                      const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
                  decoration: const BoxDecoration(
                    color: Color(0xFFF8FAFF),
                    borderRadius:
                        BorderRadius.vertical(top: Radius.circular(12)),
                  ),
                  child: const Row(
                    children: [
                      Expanded(
                        child: Text(
                          'Plant Code',
                          style: TextStyle(
                            color: Color(0xFF475569),
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                      ),
                      Text(
                        'Total Qty',
                        style: TextStyle(
                          color: Color(0xFF475569),
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                    ],
                  ),
                ),
                ...PivotEngine._plantSummary.map(
                  (row) => Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 12,
                      vertical: 14,
                    ),
                    decoration: const BoxDecoration(
                      border: Border(
                        top: BorderSide(color: Color(0xFFEFF3F8)),
                      ),
                    ),
                    child: Row(
                      children: [
                        Expanded(
                          child: Text(
                            row.$1,
                            style: const TextStyle(
                              color: Color(0xFF334155),
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                        ),
                        Text(
                          row.$2,
                          style: const TextStyle(
                            color: Color(0xFF334155),
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _LegendDatum {
  const _LegendDatum({
    required this.label,
    required this.value,
    required this.color,
    required this.percentage,
  });

  final String label;
  final String value;
  final Color color;
  final double percentage;
}

class _DonutChart extends StatelessWidget {
  const _DonutChart({required this.data});

  final List<_LegendDatum> data;

  @override
  Widget build(BuildContext context) {
    return CustomPaint(
      painter: _DonutPainter(data),
      child: const Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              '1,309',
              style: TextStyle(
                color: Color(0xFF172554),
                fontWeight: FontWeight.w800,
                fontSize: 22,
              ),
            ),
            Text(
              'Total Qty',
              style: TextStyle(
                color: Color(0xFF475569),
                fontWeight: FontWeight.w600,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _DonutPainter extends CustomPainter {
  _DonutPainter(this.data);

  final List<_LegendDatum> data;

  @override
  void paint(Canvas canvas, Size size) {
    const strokeWidth = 26.0;
    final rect = Offset.zero & size;
    final center = rect.center;
    final radius = (math.min(size.width, size.height) - strokeWidth) / 2;
    final arcRect = Rect.fromCircle(center: center, radius: radius);
    final background = Paint()
      ..color = const Color(0xFFEAF0F7)
      ..style = PaintingStyle.stroke
      ..strokeWidth = strokeWidth
      ..strokeCap = StrokeCap.round;

    canvas.drawArc(arcRect, 0, math.pi * 2, false, background);

    final paint = Paint()
      ..style = PaintingStyle.stroke
      ..strokeWidth = strokeWidth
      ..strokeCap = StrokeCap.butt;

    double startAngle = -math.pi / 2;
    for (final item in data) {
      final sweep = math.pi * 2 * item.percentage;
      paint.color = item.color;
      canvas.drawArc(arcRect, startAngle, sweep, false, paint);
      startAngle += sweep;
    }
  }

  @override
  bool shouldRepaint(covariant _DonutPainter oldDelegate) {
    return oldDelegate.data != data;
  }
}

BoxDecoration _panelDecoration() {
  return BoxDecoration(
    color: Colors.white,
    borderRadius: BorderRadius.circular(20),
    border: Border.all(color: const Color(0xFFE5EAF2)),
    boxShadow: const [
      BoxShadow(
        color: Color(0x0A0F172A),
        blurRadius: 24,
        offset: Offset(0, 10),
      ),
    ],
  );
}
