// Generated by UI Builder
// ui_builder:editable=true
import 'package:flutter/material.dart';

class PlantUpdate extends StatelessWidget {
  const PlantUpdate({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Text('plant_update.dart'),
      ),
    );
  }
}
