// Generated by UI Builder
// ui_builder:editable=true
import 'package:excelgenautomationdevo/screens/common/master_data.dart';
import 'package:excelgenautomationdevo/screens/dashboard/dispatcher_dashboard.dart';
import 'package:flutter/material.dart';

import 'dispatcher_shell.dart';
import 'pivot_engine.dart';

class PlantUpdate extends StatelessWidget {
  const PlantUpdate({super.key});

  @override
  Widget build(BuildContext context) {
    return DispatcherScaffold(
      currentItem: DispatcherNavItem.dashboard,
      onItemSelected: (item) => _handleNavigation(context, item),
      body: const Center(
        child: Text('plant_update.dart'),
      ),
    );
  }

  void _handleNavigation(BuildContext context, DispatcherNavItem item) {
    final page = switch (item) {
      DispatcherNavItem.master => const MasterData(),
      DispatcherNavItem.dashboard => const DispatcherDashboard(),
      DispatcherNavItem.pivot => const PivotEngine(),
    };

    navigateWithDispatcherTransition(context, page);
  }
}
