// Generated by UI Builder
// ui_builder:editable=true
import 'package:flutter/material.dart';

class ScheduleUpload extends StatelessWidget {
  const ScheduleUpload({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Text('schedule_upload.dart'),
      ),
    );
  }
}
