// Generated by UI Builder
// ui_builder:editable=true
import 'package:flutter/material.dart';

class UploadExcelPo extends StatelessWidget {
  const UploadExcelPo({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Text('upload_excel_po.dart'),
      ),
    );
  }
}
