// Generated by UI Builder
// ui_builder:editable=true
import 'package:flutter/material.dart';

class Billing extends StatelessWidget {
  const Billing({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Text('billing.dart'),
      ),
    );
  }
}
