// Generated by UI Builder
// ui_builder:editable=true
import 'package:flutter/material.dart';

class DispatcherDashboard extends StatelessWidget {
  const DispatcherDashboard({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Text('dispatcher_dashboard.dart'),
      ),
    );
  }
}
